# Generated by Django 2.0.4 on 2018-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltwo',
            name='upload_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
